
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  alarmSidebar: [{type: 'autogenerated', dirName: 'monitoring/alarm'}],
  eventSidebar: [{type: 'autogenerated', dirName: 'monitoring/event'}],
  trendSidebar: [{type: 'autogenerated', dirName: 'monitoring/trend'}],
};

export default sidebars;
